### ISSUE TITLE
Could not initialize class jcuda.jcufft.JCufft

### ISSUE THREAD

**Issue by rmd13** [hadim/DeconvolutionLab2#4]
I have downloaded 

jcufft-0.9.0d.jar
jcufft-natives-0.9.0d-windows-x86_64.jar
jcuda-0.9.0d.jar
jcuda-natives-0.9.0d-windows-x86_64.jar

and re-compile the java to jars.
The code could run in FFW2, academic, Jtransform, but error take place when I use jcuda version.

My computer is a basic one without dedicated graphic card, is this cause the error?

```
aNewFFT = fft.jcufft.JCuFFTLibrary; 
JCuFFTLibrary
Java exception occurred:
java.lang.NoClassDefFoundError: Could not initialize class jcuda.jcufft.JCufft

	at fft.jcufft.JCuFFTLibrary.isCudaAvailable(JCuFFTLibrary.java:85)

	at fft.jcufft.JCuFFTLibrary.<init>(JCuFFTLibrary.java:45)
```

**Comment by rmd13** [comment]
It seems that a GPU is required as seen from "isCudaAvailable".

I noticed another difference in matlab.Converter.createObject method of this fork compared with the original repo.
`public static Object createMatlabMatrix(RealSignal signal) 
`

Some people mentioned the memory leak in 2.1.2, but 2.1.1 looks like no such memory leak problem.
https://github.com/Biomedical-Imaging-Group/DeconvolutionLab2/issues/4
